# Makefile to run hello_world_11.sh

NAME=code_hello_world.sh

all:
	@echo "🔐 Decoding with base-11 HELLO WORLD mapping..."
	@bash $(NAME)

fclean:
	@rm -f $(NAME)
	@echo "🧹 Script deleted."

re: fclean all


